import Header from "./components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "BitBox",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      
      <html lang='en'>
        <body className='bg-gray-300'>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
