import Header from "./components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata = {
  title: "CodeCrewLabs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
          <html lang='en'>
          {/* <script src="https://js.pusher.com/8.0.1/pusher.min.js"></script> */}

        <body className='bg-gray-100'>
          <Header />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
